Re-render current frame after shader or node change
ninjadev/nin pull request #427
Opened 2017-06-17 19:52 UTC by lionleaf

Recompiling shaders before this fix would result in a white frame if
paused.

2017-06-24 14:07 UTC, lionleaf commented
ping

2017-07-02 12:47 UTC, stianjensen commented
I can't really see a difference in behavior with/without this fix. Do you have a suggestion for how to test it?

2017-07-30 14:58 UTC, sigvef commented
needs rebase

2021-10-25 17:12 UTC, sigvef requested changes
Rejecting for colorizer (because needs rebase).

2021-10-25 22:53 UTC, sigvef approved these changes

2021-10-25 22:53 UTC, merged